img1_path: img1_1280x960.jpeg
img2_path: img2_1280x960.jpeg
output_dir_path: outputs/img1_1280x960_img2_1280x960_pose_estimation_SIFT_maxfeat=7000_0.75_NNDR_thresh_1_2026-02-23_15-23-02
random_seed: 57
optical_focal_length_mm: 6.765
sensor_width_mm: 9.757
sensor_height_mm: 7.318
sift_edge_discard: 20
sift_max_features: 7000
sift_contrast_threshold: 0.04
sift_edge_threshold: 10
sift_n_octave_layers: 3
sift_sigma: 1.6
feature_matching_ratio_threshold: 0.75
ransac_s: 8
ransac_num_iters: 2000
triang_max_reprojection_error: 50.0
triang_min_depth: 0.01
triang_max_depth: 10000.0
launch_viser: false
